.TH MINISHELL 1 "January 2024" "42 Barcelona"

.SH NAME
minishell \- A Shell That Defies Bugs

.SH SYNOPSIS
.B minishell

.SH DESCRIPTION
.PP
\fBminishell\fR is a quirky little shell that defies the laws of bugs and embraces the chaos of command lines. It's as unpredictable as a rollercoaster ride, but hey, that's part of the fun!

.SH OPTIONS
.PP
None! Zip! Nada! Zilch! This shell is as simple as it gets. It's like trying to find a needle in a haystack, but the haystack is just... well, hay.

.SH AUTHOR
Written with love and a sprinkle of humor by Santito and Marcelito.

.SH BUGS
You'd think there would be bugs, right? Wrong! This shell is like a bug-free oasis in the desert of software. But hey, if you find one, consider it a rare collectible! 

.SH VERSION
minishell 1.0 (January 2024)

