.TH MINISHELL 1 "January 2024" "Version 1.0" "minishell manual"

.SH NAME
minishell \- a simple shell

.SH SYNOPSIS
.B minishell
[\fIOPTION\fR]...

.SH DESCRIPTION
.PP
\fBminishell\fR is a simple shell that provides basic command-line functionality.
It supports executing commands, basic shell built-ins, and simple command
pipelines.

.SH OPTIONS
.TP
\fB\-h, \-\-help\fR
Display this help message and exit.

.SH COMMANDS
.PP
\fBminishell\fR supports the following built-in commands:

.TP
\fBexit\fR
Exit the shell.

.TP
\fBcd \fIDIRECTORY\fR
Change the current working directory to \fIDIRECTORY\fR.

.SH EXAMPLES
.PP
Run a command:
.B minishell ls -l

Change directory:
.B minishell cd /path/to/directory

.SH SEE ALSO
.BR bash (1)

.SH AUTHOR
Written by Your Name.

.SH BUGS
Report bugs to Your Email Address.

.SH COPYRIGHT
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH VERSION
minishell 1.0 (January 2024)

